START cmd.exe /c node index.js c -dl
START cmd.exe /c node index.js c -dl
START cmd.exe /c node index.js c -dl
START cmd.exe /c node index.js c -dl
START cmd.exe /c node index.js c -dl
START cmd.exe /c node index.js c -dl
START cmd.exe /c node index.js c -dl
START cmd.exe /c node index.js c -dl
START cmd.exe /c node index.js c -dl
START cmd.exe /c node index.js c -dl
