START cmd.exe /c node index.js c -dlt
START cmd.exe /c node index.js c -dlt
START cmd.exe /c node index.js c -dlt
START cmd.exe /c node index.js c -dlt
START cmd.exe /c node index.js c -dlt
START cmd.exe /c node index.js c -dlt
START cmd.exe /c node index.js c -dlt
START cmd.exe /c node index.js c -dlt
START cmd.exe /c node index.js c -dlt
START cmd.exe /c node index.js c -dlt
