START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d
START cmd.exe /c node index.js c -d