
import IFactory from './fac';
import * as rawv from './raw/rawv';
import constant from './raw/const';
import grow from './raw/grow';
import growrate from './raw/growrate';
import amp from './raw/amp';
import prop from './combine/prop';
import ma from './basic/ma';
import macd from './basic/macd';
import boll from './basic/boll';
import ema from './basic/ema';
import kdj from './basic/kdj';
import rsi from './basic/rsi';
import * as math from './combine/math';
import * as logic from './combine/logic';

const factories = new Map<string, IFactory<any, any>>();

factories.set('r.start', rawv.start);
factories.set('r.end', rawv.end);
factories.set('r.high', rawv.high);
factories.set('r.low', rawv.low);
factories.set('r.ex', rawv.ex);
factories.set('r.vol', rawv.vol);
factories.set('r.marketvalue', rawv.marketvalue);
factories.set('r.netrate', rawv.netrate);
factories.set('r.const', constant);
factories.set('r.grow', grow);
factories.set('r.growrate', growrate);
factories.set('r.amp', amp);
factories.set('c.prop', prop);
factories.set('b.ma', ma);
factories.set('b.boll', boll);
factories.set('b.macd', macd);
factories.set('b.ema', ema);
factories.set('b.kdj', kdj);
factories.set('b.rsi', rsi);
factories.set('c.add', math.add);
factories.set('c.sub', math.sub);
factories.set('c.mul', math.mul);
factories.set('c.div', math.div);
factories.set('c.max', math.max);
factories.set('c.min', math.min);
factories.set('c.abs', math.abs);
factories.set('c.pow', math.pow);
factories.set('c.and', logic.and);
factories.set('c.or', logic.or);
factories.set('c.eq', logic.eq);
factories.set('c.gt', logic.gt);
factories.set('c.gte', logic.gte);
factories.set('c.lt', logic.lt);
factories.set('c.lte', logic.lte);
factories.set('c.between', logic.between);
factories.set('c.not', logic.not);

export default factories;
